### ISSUE TITLE
Function 'zlistx_head' not found

### ISSUE THREAD

**Issue by tpitale** [celluloid/celluloid-zmq#61]
Updated to master to try the new cztop version of celluloid-zmq. Getting this error:

```
/Users/tpitale/.gem/ruby/2.2.2/gems/ffi-1.9.10/lib/ffi/library.rb:261:in `attach_function': Function 'zlistx_head' not found in [/usr/local/lib/libczmq.dylib] (FFI::NotFoundError)
    from /Users/tpitale/.gem/ruby/2.2.2/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:410:in `<module:FFI>'
    from /Users/tpitale/.gem/ruby/2.2.2/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:10:in `<module:CZMQ>'
    from /Users/tpitale/.gem/ruby/2.2.2/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:9:in `<top (required)>'
    from /Users/tpitale/.gem/ruby/2.2.2/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:1:in `require_relative'
    from /Users/tpitale/.gem/ruby/2.2.2/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:1:in `<top (required)>'
    from /Users/tpitale/.gem/ruby/2.2.2/gems/cztop-0.4.0/lib/cztop.rb:1:in `require'
    from /Users/tpitale/.gem/ruby/2.2.2/gems/cztop-0.4.0/lib/cztop.rb:1:in `<top (required)>'
    from /Users/tpitale/.gem/ruby/2.2.2/bundler/gems/celluloid-zmq-6e4b9eded922/lib/celluloid/zmq.rb:1:in `require'
    from /Users/tpitale/.gem/ruby/2.2.2/bundler/gems/celluloid-zmq-6e4b9eded922/lib/celluloid/zmq.rb:1:in `<top (required)>'
    from /Users/tpitale/.gem/ruby/2.2.2/bundler/gems/celluloid-zmq-6e4b9eded922/lib/celluloid/zmq/current.rb:2:in `require'
    from /Users/tpitale/.gem/ruby/2.2.2/bundler/gems/celluloid-zmq-6e4b9eded922/lib/celluloid/zmq/current.rb:2:in `<top (required)>'
```

Running MRI 2.2.2, FFI 1.9.10 (appears to be the latest release).

**Comment by tpitale** [comment]
This may be an issue I should open on cztop, but I wanted to start here since this was a recent change to celluloid-zmq. /cc @paddor

**Comment by tpitale** [comment]
Needed cztop to be on HEAD of czmq and zmq.

**Comment by paddor** [comment]
@tpitale Yeah, CZTop requires current master of czmq and zmq. This should change with the next release of ZMQ (will be 4.2, if I'm not mistaken) and CZMQ (no idea what the version will be).
